"""Tests for report conversion helpers."""

import json
import uuid
from pathlib import Path

from click.testing import CliRunner
import pytest

from bundleInspector.cli import _parse_report_content_for_convert, main
from bundleInspector.reporter.html_reporter import HTMLReporter
from bundleInspector.reporter.json_reporter import JSONReporter
from bundleInspector.storage.models import (
    Category,
    Confidence,
    Evidence,
    Finding,
    Report,
    RiskTier,
    Severity,
    JSAsset,
)


TEST_TMP_ROOT = Path(".tmp_test_artifacts")
TEST_TMP_ROOT.mkdir(parents=True, exist_ok=True)


def _make_test_path(name: str) -> Path:
    """Create a unique workspace-local path for CLI convert tests."""
    return (TEST_TMP_ROOT / f"{uuid.uuid4().hex}_{name}").resolve()


def _build_report() -> Report:
    finding = Finding(
        rule_id="endpoint-detector",
        category=Category.ENDPOINT,
        severity=Severity.INFO,
        confidence=Confidence.HIGH,
        title="API Endpoint",
        description="Test endpoint",
        evidence=Evidence(
            file_url="https://example.com/app.js",
            file_hash="abc123",
            line=10,
            snippet='fetch("/api/users")',
        ),
        extracted_value="/api/users",
        risk_tier=RiskTier.P3,
        risk_score=1.0,
    )
    report = Report(
        seed_urls=["https://example.com"],
        findings=[finding],
    )
    report.compute_summary()
    return report


def _build_original_source_report() -> Report:
    finding = Finding(
        rule_id="endpoint-detector",
        category=Category.ENDPOINT,
        severity=Severity.MEDIUM,
        confidence=Confidence.HIGH,
        title="Source-mapped Endpoint",
        description="Endpoint with original source evidence",
        evidence=Evidence(
            file_url="https://example.com/static/app.js",
            file_hash="abc123",
            line=40,
            column=2,
            snippet='fetch("/api/users")',
            snippet_lines=(39, 41),
            original_file_url="src/app.ts",
            original_line=12,
            original_column=4,
        ),
        extracted_value="/api/users",
        risk_tier=RiskTier.P2,
        risk_score=5.0,
        metadata={
            "original_snippet": 'const endpoint = "/api/users";',
            "original_snippet_lines": [11, 13],
        },
    )
    report = Report(
        seed_urls=["https://example.com"],
        findings=[finding],
        assets=[
            JSAsset(
                url="file:///bundle.js",
                content_hash="hash-bundle",
                content=b'console.log("raw secret bytes")',
            )
        ],
    )
    report.compute_summary()
    return report


def test_load_report_from_embedded_html():
    """HTML generated by BundleInspector should round-trip back into a Report."""
    report = _build_report()
    html = HTMLReporter().generate(report)
    loaded = _parse_report_content_for_convert(html)

    assert loaded.summary.total_findings == 1
    assert loaded.findings[0].extracted_value == "/api/users"


def test_load_report_from_html_without_embedded_json_raises():
    """Non-BundleInspector HTML should fail with a clear error."""
    with pytest.raises(Exception):
        _parse_report_content_for_convert("<html><body>No embedded report</body></html>")


def test_convert_command_round_trips_html_and_preserves_original_evidence():
    """CLI convert should round-trip JSON->HTML->JSON without leaking raw assets and while preserving source-mapped evidence."""
    report = _build_original_source_report()
    input_json = _make_test_path("report.json")
    output_html = _make_test_path("report.html")
    output_json = _make_test_path("roundtrip.json")
    input_json.write_text(JSONReporter(include_raw=True).generate(report), encoding="utf-8")

    runner = CliRunner()
    to_html = runner.invoke(
        main,
        ["convert", str(input_json), "--format", "html", "--output", str(output_html)],
    )
    assert to_html.exit_code == 0, to_html.output

    html = output_html.read_text(encoding="utf-8")
    assert "raw secret bytes" not in html

    to_json = runner.invoke(
        main,
        ["convert", str(output_html), "--format", "json", "--output", str(output_json)],
    )
    assert to_json.exit_code == 0, to_json.output

    data = json.loads(output_json.read_text(encoding="utf-8"))
    finding = data["findings"][0]

    assert finding["evidence"]["file_url"] == "src/app.ts"
    assert finding["evidence"]["line"] == 12
    assert finding["evidence"]["column"] == 4
    assert finding["evidence"]["snippet"] == 'const endpoint = "/api/users";'
    assert finding["metadata"]["normalized_evidence"]["file_url"] == "https://example.com/static/app.js"
    assert "content" not in data["assets"][0]

